require conf/distro/include/pironman5.inc

DISTRO = "pironman5-promax"

# Fix recipe versions for reproducible Pro Max builds.
PREFERRED_VERSION_python3-pironman5 = "1.3.7"
PREFERRED_VERSION_python3-pm-auto = "1.4.7"
PREFERRED_VERSION_python3-pm-dashboard = "1.4.0"
PREFERRED_VERSION_python3-sf-rpi-status = "1.1.8"

DT_OVERLAYS = "sunfounder-pironman5promax.dtbo"

###############################################################################
# promax specific settings.

# 1: Display settings
ENABLE_DSI_DISPLAY="1"
ENABLE_DUAL_DISPLAY ?= "0"

ENABLE_CAMERA="1"
CAMERA_AUTO_DETECT="1"

###############################################################################
# Raspberry Pi camera overlay set in meta-raspberrypi doesn't include ov5647 by default.
RPI_KERNEL_DEVICETREE_OVERLAYS:append = " overlays/ov5647.dtbo"

# Optional explicit camera settings consumed by rpi-config_git.bbappend.
CAMERA_AUTO_DETECT = "1"
CAMERA_OVERLAY = "ov5647,cam0"

# camera apps
# the current version of libcamera-apps need to adopt to libcamera 0.5.2 API.
PREFERRED_VERSION_libcamera-apps = "1.9.0"
